### ISSUE TITLE
A=11 is interpreted as Equal[A,11], and A==11 and A===1 raise a SyntaxError

### ISSUE THREAD

**Issue by mmatera** [Mathics3/mathicsscript#18]
@rocky @GarkGarcia, this seems to be connected with the new mathics-scanner
```
In[1]:= A=11//FullForm
Out[1]= Equal[A, 11]

In[2]:= A==11//FullForm
Syntax::sntxf: "A" cannot be followed by "11//FullForm" (line 1 of "<stdin>").
In[2]:= A===11
Syntax::sntxf: "A" cannot be followed by "11" (line 1 of "<stdin>").
```

**Comment by rocky** [comment]
Probably the `esc-alias`  `==` is interfering here in the routine that is automatically converting things.  I am not sure what @GarkGarcia did to fix this with the other cases where we had this. 

There is a better way to handle all of this.  We haven't gotten there. But when the massive tables were created, it maximized the possibility that this thing we didn't have control would cause the maximum amount of breakage.

**Comment by GarkGarcia** [comment]
@rocky It was an error in the YAML table, `\[LongEqual]` had `has-unicode-inverse` set to `true` and it should be `false`. I had fixed this already in the past, but I guess the fix was overwritten when I was converting the data to YAML.

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/Mathics3/mathics-scanner/commit/306822a9505d1dbdca9995f7e9fad38e880a1248.

**Comment by GarkGarcia** [comment]
> We haven't gotten there. But when the massive tables were created, it maximized the possibility that this thing we didn't have mastery over would cause the maximum amount of breakage.

I agree that the creating of the massive tables was prone to cause problems, but keep in mind the systematic approach of the tables also makes it much easier to fix them and maintain the code. 

All of the errors we've encountered so far are errors in the translation tables, which were caused either by me (I filled in about 70% of the 1004 entries in the table by hand, which is prone to errors) or by CSV-escaping errors in conversion scripts used along the way. This errors are quite easy to fix now that we have a single source of truth (`named-characters.yml`). Just look at https://github.com/Mathics3/mathics-scanner/commit/306822a9505d1dbdca9995f7e9fad38e880a1248, all we had to do is change a single line.

**Comment by GarkGarcia** [comment]
All in all, we are likely to find more errors in the translation tables in the near future, but they are easy to fix and over time the they will be fixed and we won't have to worry about them ever again.

**Comment by mmatera** [comment]
Could be possible to take the test cases from the documentation, and test the translation automatically?

**Comment by GarkGarcia** [comment]
> Could be possible to take the test cases from the documentation, and test the translation automatically?

That's my plan (steal the tests from core), but we'll have to adapt them a bit.
