### ISSUE TITLE
Anonymous functions broken in mathicsscript

### ISSUE THREAD

**Issue by srossd** [Mathics3/mathicsscript#27]
In mathics:
```
In[1]:= # ^ 2 & /@ Range[5]
Out[1]= {1, 4, 9, 16, 25}
```

But in mathicsscript:
```
In[1]:= # ^ 2 & /@ Range[5]
Syntax::sntxb: Expression cannot begin with " ^ 2 & /@ Range[5]" (line 1 of "<stdin>").
```

**Comment by rocky** [comment]
@srossd This is a problem in Mathicsscanner and how the NumberSign (#) is tagged.

If you install that from git making sure it generates  a new `mathics_scanner/data/characters.json` you should be ine.
