### ISSUE TITLE
Missing a license

### ISSUE THREAD

**Issue by Techcable** [Mathics3/mathicsscript#28]
The AUR package format wants a 'license' field. For now, I've listed it as 'custom' since there is nothing in the repository.

I'm assuming it's GPL compatible since that is what 'mathics' is licensed under.

**Comment by rocky** [comment]
Yes, GPL3 like the rest. COPYING.txt should now be there with 06aef70. 

(It was listed in MANIFEST.in already. I guess `twine check` doesn't give a warning about such mismatches). 

BTW - thanks for packaging for AUR. I see you guys are much more on top of packaging compared to everyone else - Thanks!
