### ISSUE TITLE
Is there an option to disable Mathics autoclosing parentheses?

### ISSUE THREAD

**Issue by DUOLabs333** [Mathics3/mathicsscript#55]
I'm willing to work on this.

**Comment by rocky** [comment]
Great - The default readline code is https://github.com/Mathics3/mathicsscript/blob/master/mathicsscript/termshell_prompt.py

A list of all things settable is in https://github.com/Mathics3/mathicsscript/blob/master/mathicsscript/autoload/settings.m should we decide to put add this as a setting.

**Comment by DUOLabs333** [comment]
There seems to be this: `if not hasattr(event.app, "group_autocomplete")`, so there is a place where the autopair is set.

**Comment by DUOLabs333** [comment]
Ironically enough, there's a `# TODO: Figure out how allow user-customization`, so I guess that's where I come in :)

**Comment by DUOLabs333** [comment]
How do I load the value of a Setting?

**Comment by DUOLabs333** [comment]
Also, is there a file in the home directory mathics reads on load?

**Comment by mmatera** [comment]
@DUOLabs333: There is a file  `mathicsscript/autoload/settings.m` folder. In that file is where the options should be specified, in terms of setting WL variables. Then, in the frontend, you can look at such variables.

**Comment by mmatera** [comment]
Looks for instance the variable ```Settings`PygmentsShowTokens``` and how it is used.

**Comment by DUOLabs333** [comment]
Where should `mathicsscript/autoload/settings.m` be placed? In the project directory itself?

**Comment by DUOLabs333** [comment]
However, the PR does break the ability for me to type in `}`. I can do `)` and `]` quite fine though.

**Comment by mmatera** [comment]
If you want a Python boolean value, 
``self.definitions.get_ownvalue("Settings`$GroupAutocomplete").to_python()`` or
``self.definitions.get_ownvalue("Settings`$GroupAutocomplete").is_true()``

**Comment by rocky** [comment]
Fixed in #60
