### ISSUE TITLE
Extra closing brackets with autocomplete

### ISSUE THREAD

**Issue by adamantinum** [Mathics3/mathicsscript#63]
Hi,
After commit fb7c99708fb6e6a35b649cacaa2dc4c1f2f749fa when writing closing brackets, mathicsscript writes extra brackets instead of closing those ones already matched

Expected behaviour:
Print["Hello"_]_ -> type ] -> Print["Hello"]

Actual behaviour:
Print["Hello"_]_ -> type ] -> Print["Hello]]
where the brackets in italic are the autocompleted ones.

In the previous commit 59bf1d708fe32ee03cfa049bfb6d41cebb986bee the issue does not occur.

**Comment by rocky** [comment]
Please work up a PR for this and that will satisfy both you and @DUOLabs333

**Comment by DUOLabs333** [comment]
@rocky ? I don't have a problem with this.

**Comment by DUOLabs333** [comment]
I don't have this problem.

**Comment by DUOLabs333** [comment]
@adamantinum Do you mean that when mathicsscript completes a bracket, you type a bracket, and expect the extra one to disappear?

**Comment by adamantinum** [comment]
I think it would be useful revert the commit. Maybe I would fix the wrong behaviour when closing "}" with autocomplete disabled.
I should add an else in the deleted part, just as it's for the other closing brackets.
`@bindings.add("}")
 def curly_right(event):
     b = event.cli.current_buffer
     if not hasattr(event.app, "group_autocomplete"):
         b.insert_text("}")
         return
     if event.app.group_autocomplete:
         char = b.document.current_char
         if char == "}":
             b.cursor_right()
         else:
             b.insert_text("}")
     **else:
         b.insert_text("}")**
`

**Comment by adamantinum** [comment]
> @adamantinum Do you mean that when mathicsscript completes a bracket, you type a bracket, and expect the extra one to disappear?

Yes, as it was before that commit, when I "manually" close a bracket, that one written by the autocomplete disappers

**Comment by adamantinum** [comment]
> I think it would be useful revert the commit. Maybe I would fix the wrong behaviour when closing "}" with autocomplete disabled. I should add an else in the deleted part, just as it's for the other closing brackets.
> 
> ```
> @bindings.add("}")
>  def curly_right(event):
>      b = event.cli.current_buffer
>      if not hasattr(event.app, "group_autocomplete"):
>          b.insert_text("}")
>          return
>      if event.app.group_autocomplete:
>          char = b.document.current_char
>          if char == "}":
>              b.cursor_right()
>          else:
>              b.insert_text("}")
>       else:                              # this
>          b.insert_text("}")         # and that
> ```

@rocky if it's okay, I may add bindings to autocomplete quotation marks too.

**Comment by rocky** [comment]
@adamantinum Sure - have at it! 

That part that is worrisome to me when one person does something that then another person objects to. If we could all be mindful that the way you prefer have things set up may not be match someone else's preference and have some sort of mechanism by which not just your preference is satisfied but allows for someone else's preference, that would be awesome.

**Comment by adamantinum** [comment]
> @adamantinum Sure - have at it!
> 
> That part that is worrisome to me when one person does something that then another person objects to. If we could all be mindful that the way you prefer have things set up may not be match someone else's preference and have some sort of mechanism by which not just your preference is satisfied but allows for someone else's preference, that would be awesome.

I understand what you say and you're right. I opened the issue because the expected behaviour is that one of the most of autocomplete systems (e.g. Jupyter).
Maybe, before I proceed restoring the deleted bindings, @DUOLabs333 can explain the reason of his commit and why he tought bindings for right parenthesis were not needed...

**Comment by TiagoCavalcante** [comment]
@rocky I agree with @adamantinum , if you type space in your keyboard, how much spaces you expect to appear?

**Comment by rocky** [comment]
Personally, I don't have an opinion or care, although I totally understand that others feel strongly about this. So that's why I'd prefer all the parties with strong opinion opinions to come to an agreement on some approach that is mutually agreeable. If it requires adding settings or setting setting some way so be it. 

After there's agreement then I suspect it will be straightforward to implement that. (But it would be nice to have a volunteer to fix. Hmmm. maybe a have an issue tag for that?)

**Comment by TiagoCavalcante** [comment]
@rocky after @adamantinum implement the fix, I believe @DUOLabs333 will also agree that the new behavior is correct.

**Comment by adamantinum** [comment]
> @rocky after @adamantinum implement the fix, I believe @DUOLabs333 will also agree that the new behavior is correct.

Sorry, now I'm a bit confused. If you talking about the fix in my former comment I think it should be fine, since it doesn't modify the possibility to disable autobrace (and since @DUOLabs333 said he has disabled it, this shouldn't affect his user experience).

**Comment by TiagoCavalcante** [comment]
@adamantinum could you make a PR with the fix from your comment?

**Comment by adamantinum** [comment]
> @adamantinum could you make a PR with the fix from your comment?

Sure, I was waiting for confirmation.
Moreover, I'm searching if there is some variable in which settings are stored, so I could replace that chain of if statement with a more fancy `@Condition` as described in prompt_toolkit docs
https://python-prompt-toolkit.readthedocs.io/en/master/pages/advanced_topics/key_bindings.html#attaching-a-filter-condition

**Comment by DUOLabs333** [comment]
I deleted the bindings because for some reason, they prevented me from adding right braces. Maybe this patch fixes though.

**Comment by TiagoCavalcante** [comment]
@adamantinum is this what you are looking for?

https://github.com/Mathics3/mathicsscript/blob/b124a660990ca01dd9da6913143e28ec686d8e1b/mathicsscript/__main__.py#L366

**Comment by adamantinum** [comment]
> @adamantinum is this what you are looking for?
> 
> https://github.com/Mathics3/mathicsscript/blob/b124a660990ca01dd9da6913143e28ec686d8e1b/mathicsscript/__main__.py#L366

Yes I was looking for that one with $GroupAutocomplete instead of $PygmentsStyle
The issue I was trying to solve was that seems settings are stored inside `shell`, that is initialized in __main__, so in bindkeys.py neither there is a way to check the status of variables, nor I can import `shell` from __main__.
If this isn't implemented in prompt_toolkit itself, I suppose I have to keep the original version of the fix.

**Comment by TiagoCavalcante** [comment]
@adamantinum the definitions are stored here:
 https://github.com/Mathics3/mathicsscript/blob/b124a660990ca01dd9da6913143e28ec686d8e1b/mathicsscript/__main__.py#L243

you can move it to another file and import that from __main__ and from the other file.

**Comment by adamantinum** [comment]
> @adamantinum the definitions are stored here:
> 
> https://github.com/Mathics3/mathicsscript/blob/b124a660990ca01dd9da6913143e28ec686d8e1b/mathicsscript/__main__.py#L243
> 
> you can move it to another file and import that from **main** and from the other file.

Thank you, it works in this way

**Comment by rocky** [comment]
@adamantinum thanks for doing - I will try to look at this next weekend.

**Comment by TiagoCavalcante** [comment]
>  It's a bit ugly adding a file for a single initialization, but if there is no other manner...

@adamantinum I guess that is the only way, otherwise, we would either have a circular import, or a declaration in a crazy place.  
In Python, this may not be common, but we do it a lot in React (with zustand stores) and it is the recommendation in SolidJS.

**Comment by adamantinum** [comment]
Solved with merging of https://github.com/Mathics3/mathicsscript/pull/64
