### ISSUE TITLE
Missing requirements-{dev,full}.txt in release 6.0.0

### ISSUE THREAD

**Issue by vicp74** [Mathics3/mathicsscript#73]
Files [requirements-dev.txt](https://github.com/Mathics3/mathicsscript/blob/6.0.0/requirements-dev.txt) and [requirements-full.txt](https://github.com/Mathics3/mathicsscript/blob/6.0.0/requirements-full.txt) are missing in the .tar.gz package for version 6.0.0: [mathicsscript-6.0.0.tar.gz](https://github.com/Mathics3/mathicsscript/releases/download/6.0.0/mathicsscript-6.0.0.tar.gz)

I now maintain this package in [AUR](https://aur.archlinux.org/packages/mathicsscript) and I've made it work by manually downloading those files. However adding them in the .tar.gz would make for a cleaner process.

Thanks for the hard work!

**Comment by rocky** [comment]
Thanks for packaging this on AUR!

There seems to be some controversy as to how to handle this. See https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py

Possibly the accepted answer is the one we should use? Comments?

**Comment by vicp74** [comment]
Thanks for the link, very interesting!

Even taking into account the accepted answer, which I don't think I agree with, the problem is that if I don't download the `requirement-*.txt` files, that info in nowhere to be found. Or is it? Because you didn't duplicate the requirements, but instead sourced those files in `setup.py`.

Maybe there's something I'm missing because I can't use `pip` when packaging for Arch, otherwise the package manager cannot track the installed files. You can check the guidelines [here](https://wiki.archlinux.org/title/Python_package_guidelines#setuptools_or_distutils). When there's no `pyproject.toml`, such as in this case, they consist of basically calling `setup.py build` and `install`.

I think that either all the requirements should be really duplicated, as in explicitly written, in both `setup.py` and any `requirement.txt`, or I need both files. If you see any other way, please let me know.

**Comment by rocky** [comment]
@vicp74 See if #74 works for you.

**Comment by vicp74** [comment]
Ok, if that's enough to ship those two files in the tarfile, that'd solve this issue. Thanks!

**Comment by rocky** [comment]
Great - problem solved - for now.
