### ISSUE TITLE
Cannot find setting named 'lsp'

### ISSUE THREAD

**Issue by mickmcq** [Mathics3/mathicsscript#84]
## Description

When I start mathicsscript, the first line that appears is

In[1]:= Cannot find setting named 'lsp'

Yet the string 'lsp' doesn't seem to appear in the Mathicsscript 7.0.0 code, so I'm not sure how to approach it.

## How to Reproduce

mathicsscript

## Output Given

Mathicscript: 7.0.0, Mathics 7.0.0
on CPython 3.12.6 (main, Sep 13 2024, 14:10:34) [Clang 15.0.0 (clang-1500.1.0.2.5)]

Using:
SymPy 1.12.1, mpmath 1.3.0, numpy 1.26.4
cython 3.0.11, matplotlib 3.10.0,
Asymptote version 2.88

Copyright (C) 2011-2024 The Mathics Team.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions.
See the documentation for the full license.

Quit by evaluating Quit[] or by pressing CONTROL-D.

In[1]:= Cannot find setting named 'lsp'

## Expected behavior

In[1]:=

## Your Environment

Installed from pip on 2024-12-14 with latest dependencies as far as I know

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser none, using iTerm2 as a terminal

## Workarounds

None that I know of

## Priority

Probably low

## Additional context

Python novice; Mathics newb

**Comment by rocky** [comment]
I've never encountered this. I suspect this message comes from software outside of what one thinks of as Mathics3, like a readline library, or iTerm2. 

Do you get this message when running:

* `mathics`
* `mathicsscript --readline None`
* `mathicsscript --readline GNU`
* `mathicsscript --readline Prompt`
?

And the name `lsp` is weird. It is not something Mathics3 sets or looks for as far as I know. Do you have an environment variable with either a name `lsp` or that has a value `lsp`?  "lsp" as far as I know stands for (Microsoft's) language server protocol.

**Comment by mickmcq** [comment]
It does not appear when I run mathics
It does appear with each of the three --readline options you mentioned

I have no environment variables or values of lsp. Nothing in my .bash_profile nor .bashrc seems to explain it.

I did google it and some pages related to Emacs came up. I see that I can toggle Emacs / Vi mode with F4 but I can't figure out how to start in Vi mode to see if that helps.

**Comment by rocky** [comment]
Ok - thanks for the information. Given that this is not specific to readline routine, my next guess is getting triggered based on the terminal you are using iterm2.

Can you run from another kind of terminal? Or from inside a GNU emacs shell and still see this? 

Also, it might be coming from a program that tries to figure out if your terminal has a light or dark background. So try this: 

```$ python 
Python 3.12.7 (main, Oct  4 2024, 21:41:28) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from term_background.__main__ import is_dark_background
>>> is_dark_background()
False # or maybe True
>>> 
```

When all else fails, there is just running this from the outset with a debugger(or adding `print()` statements in the code  and stepping through the program to narrow where this is coming from.

**Comment by mickmcq** [comment]
I did try terminal on two machines, one arm64 and one intel, with the same results.
I just got True from the Python chunk you suggested.
I'm not sure how to even run mathicsscript with a debugger. I haven't really programmed in years! (Would gdb work? If so, what file would I run it on?) By the way, is it possible to start in Vi mode? I don't have Emacs on either machine but I do wonder if Emacs editing mode is involved.

**Comment by mickmcq** [comment]
Okay, I found pdb and seem to be able to step through __main__.py by repeatedly pressing n. For context, here are a few lines before "Cannot find setting named 'lsp'" appears:

> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/site-packages/mathicsscript/__main__.py(39)<module>()
-> from mathicsscript.format import format_output, matplotlib_version
(Pdb) n
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/site-packages/mathicsscript/__main__.py(41)<module>()
-> version_string = """Mathics {mathics}
(Pdb) Cannot find setting named 'lsp'

Does this make any sense to you?

**Comment by rocky** [comment]
> Okay, I found pdb and seem to be able to step through `__main__.py` by repeatedly pressing n. For context, here are a few lines before "Cannot find setting named 'lsp'" appears:
> 
> ```
> > /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/site-packages/mathicsscript/__main__.py(39)<module>()
> -> from mathicsscript.format import format_output, matplotlib_version
> (Pdb) n
> > /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/site-packages/mathicsscript/__main__.py(41)<module>()
> -> version_string = """Mathics {mathics}
> (Pdb) Cannot find setting named 'lsp'
> ```
> 
> Does this make any sense to you?

Yes, istead of using "n" (step over), use "s" (step into) and you'll narrow better where that message is coming from.

**Comment by mickmcq** [comment]
Okay, I must have pressed 's' a million times, but it eventually reached this:

```
--Return--
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1882)<genexpr>()->None
-> for dir in os.get_exec_path(env))
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1883)_execute_child()
-> fds_to_keep = set(pass_fds)
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1884)_execute_child()
-> fds_to_keep.add(errpipe_write)
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1885)_execute_child()
-> self.pid = _fork_exec(
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1886)_execute_child()
-> args, executable_list,
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1887)_execute_child()
-> close_fds, tuple(sorted(map(int, fds_to_keep))),
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1888)_execute_child()
-> cwd, env_list,
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1889)_execute_child()
-> p2cread, p2cwrite, c2pread, c2pwrite,
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1890)_execute_child()
-> errread, errwrite,
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1891)_execute_child()
-> errpipe_read, errpipe_write,
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1892)_execute_child()
-> restore_signals, start_new_session,
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1893)_execute_child()
-> process_group, gid, gids, uid, umask,
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1894)_execute_child()
-> preexec_fn, _USE_VFORK)
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1885)_execute_child()
-> self.pid = _fork_exec(
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1895)_execute_child()
-> self._child_created = True
(Pdb) Cannot find setting named 'lsp'
s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1898)_execute_child()
-> os.close(errpipe_write)
(Pdb) s
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1900)_execute_child()
-> self._close_pipe_fds(p2cread, p2cwrite,
(Pdb)
```

**Comment by rocky** [comment]
> Okay, I must have pressed 's' a million times, but it eventually reached this:

Sigh. Thanks for being a good sport. 

The intent was not to make things difficult here but to find out what is going on. And in doing this it does help to have a little bit of an understanding the situation.  And possibly how to debug programs, and Python programs in particular.

The kind of situation we though was happening is confirmed by what you show in the pdb trace: that this message is appearing as a result of some other external command that is getting used to provide some sort of information. Like whether you have a dark background in your terminal. Or maybe what kinds of pygments styling is available in your environment. 

The information we need is _what_ command is getting run. And that information can be found when stopped here: 

```
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1885)_execute_child()
-> self.pid = _fork_exec(
```
The is near the place where the external command is getting run. (the actual run point is a few steps further as you report.)

The name of the command and the parameters are in variables `args`, and `executable_list`. (Other possibly useful information might be `cwd` (if there is a possibly that this command can come from several places depending on your current working directory), and `env_list` (which I guess is passing some sort of environment which might influence program resolution, again when there are several possibilities.)

However the _most_ important piece of information is _what program is getting run_ and that is probably found in the variables `args` and `executable_list`.  Probably in the step information from before there was some indication of why were were trying to run this external program to.

At any rate, when you get to 

```
> /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py(1885)_execute_child()
-> self.pid = _fork_exec(
```

You want to enter the two debugger commands:

```
(Pdb) p args
(Pdb) p executable_list
```

To save you from having to type `s` a million times to get to that spot, you can use "n" up until the point were you get the message. And then the _next_ time step into, and run next up until, etc.   

Alternatively, and probably better if it works, there is a "b" (break) command so you might be able to type: 

```
(Pdb) b  /Users/mm223266/.pyenv/versions/3.12.6/lib/python3.12/subprocess.py:1885
(Pdb) c
```

That might take a long time  to run. It might not though. 

Again, thanks for being a good sport about this. 
```
```


```

**Comment by mickmcq** [comment]
Thank You! That seems to have solved the problem.

It seems that mathicsscript is looking for a program called asy and finds it at /usr/local/texlive/2024/bin/universal-darwin/asy, which is a program for graphics that is often used with LaTeX. When I move asy out of the path, the error goes away. I just wish I could keep asy in that location for future use, but I can instead put it in another place. I'm not likely to forget it!

**Comment by rocky** [comment]
Something is fishy here. mathicsscript can use "asy" for drawing 3D graphics. So it would be better to keep asy where it is and find out why asymptote gives that message. 

Because you followed the issue template instructions, I see that you are running asymptote 2.88. I have been running 2.87  so there is a small possibility that something needs to be adjusted for aymptote 2.88 as opposed to 2.87.

**Comment by mickmcq** [comment]
I just installed asy (2.95) from homebrew and it is recognized by mathicsscript and there is no error message. So now all I need is to be able start up in Vi mode and I'm happy. I see how to say app.editing_mode = EditingMode.VI but I'm not sure where I would put that.

**Comment by rocky** [comment]
Currently the program uses whatever the readline library sets initially. And apparently, Emacs is the default. 

There should be a command-line option to be able to specify which readlne mode you want to start at. 

But this is a different aspect. Please open a feature request for that.  And feel free to put in a pull request (PR) for that as well.

**Comment by mickmcq** [comment]
Okay, I'll open a feature request, but I think it is only needed when prompt_toolkit is the input. It's the default as far as I can tell but if I switch to GNU readline, my .inputrc file is read, which can control the editing mode. prompt_toolkit appears to have no configuration file like .inputrc that is read on startup, but it's much nicer than GNU readline, so I would rather use it.
